export const exampleFleetOne = [
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  ["frigate", "resistojet", "small_cannons", "small_cannons", "small_cannons"],
  [
    "dreadnought",
    "resistojet",
    "large_cannons",
    "large_cannons",
    "large_cannons",
    "large_cannons",
    "small_cannons",
    "small_cannons",
    "radio",
    "radar",
  ],
];

export const exampleFleetTwo = [
  [
    "light_cruiser",
    "resistojet",
    "small_cannons",
    "small_cannons",
    "small_cannons",
    "small_cannons",
  ],
  [
    "light_cruiser",
    "resistojet",
    "small_cannons",
    "small_cannons",
    "small_cannons",
    "small_cannons",
  ],
  [
    "light_cruiser",
    "resistojet",
    "small_cannons",
    "small_cannons",
    "small_cannons",
    "small_cannons",
  ],
  [
    "light_cruiser",
    "resistojet",
    "small_cannons",
    "small_cannons",
    "small_cannons",
    "small_cannons",
  ],
  [
    "light_cruiser",
    "resistojet",
    "small_cannons",
    "small_cannons",
    "small_cannons",
    "small_cannons",
  ],
  [
    "light_cruiser",
    "resistojet",
    "small_cannons",
    "small_cannons",
    "small_cannons",
    "small_cannons",
  ],
  [
    "light_cruiser",
    "resistojet",
    "small_cannons",
    "small_cannons",
    "small_cannons",
    "small_cannons",
  ],
  [
    "light_cruiser",
    "resistojet",
    "small_cannons",
    "small_cannons",
    "small_cannons",
    "small_cannons",
  ],
  [
    "light_cruiser",
    "resistojet",
    "small_cannons",
    "small_cannons",
    "small_cannons",
    "small_cannons",
  ],
  [
    "dreadnought",
    "resistojet",
    "large_cannons",
    "large_cannons",
    "large_cannons",
    "large_cannons",
    "small_cannons",
    "small_cannons",
    "radio",
    "radar",
  ],
];
